### PR TITLE
zend had the great idea to move all their github repositories...

### PR DESCRIPTION
**Pull request by dbu**
with this, things install again.

i had to edit the lock file manually, a simple composer update leads to a quite broken system (urls can not be generated anymore, and admin has no css/js anymore)

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Great title.

**Comment by dbu** [comment]
i admit i was a bit annoyed when i figured out what had happened... but
well, it was actually not difficult to rename the paths in the composer.lock

**Comment by ElectricMaxxx** [comment]
But i think i told the reason when detecting that issue while implementing the vagrant stuff. :p

**Comment by dbu** [comment]
ah right. somehow forgot about it again. we seem to have a big issue when running composer update, i guess we have to solve that asap (first step figure out what the reason for breaking is).

**Pull request merged**
