### PR TITLE
Adding dependency badge to README

### PR DESCRIPTION
**Pull request by reiz**

### CODE REVIEW

**Comment by lsmith77** [comment]
@symfony-cmf/contributors what do you all think of this? guess it doesn't hurt .. f.e. I didnt realize that ElFinderBundle has been releasing so many new major version numbers ..

**Comment by Crell** [comment]
The diff is a bit hard to read, but I've no issue with having status badges in the readme.

**Comment by dinamic** [comment]
Looks cool and may proof useful to someone. I can't think of a reason why we might not want it.
+1 from me.

**Comment by reiz** [comment]
@dinamic @Crell @lsmith77 Thanks guys :+1:

**Pull request merged**
