### PR TITLE
Make build run again in fix_master branch

### PR DESCRIPTION
**Pull request by SenseException**
This PR is about a suggestion for the described problem in #397, where a travis-ci builds just stop. This PR is not about making the tests go green, but to make the build run till the end again.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
yea nice, now we do see the issue :-) cool.

**Comment by dbu** [comment]
thanks @SenseException !

can you try to fix the styleci issues please?

looks like sonata cache expects a method getDocument to exist on the PreUpdateEventArgs of phpcr-odm. i created https://github.com/sonata-project/cache/pull/103 - i think that sonata cache invalidator never worked.

on our end, i think we should not be running any active sonata cache invalidation. is it coming from sonata admin?

**Comment by SenseException** [comment]
> can you try to fix the styleci issues please?

Done

**Comment by ElectricMaxxx** [comment]
I will merge this one into master at all, as it makes the test better.

**Pull request merged**
