### PR TITLE
updating dependencies

### PR DESCRIPTION
**Pull request by dbu**
* fixed version of SonataTranslationBundle

### CODE REVIEW

**Comment by dbu** [comment]
hm. i propose we ditch php 5.3 for the sandbox, ok?

**Comment by WouterJ** [comment]
Does `1.0.0|^1.02` work? Otherwise, yeah let's drop 5.3

**Comment by dbu** [comment]
okay, works!

lets wait for SeoBundle to be ready, then i update one more time.

**Comment by dbu** [comment]
i think we are getting there! updated everything including seo 1.2.0. did a quick test locally adding a new translation in the admin. all seems to work fine!

next + last step is i will add the release news fo the cmf website.

**Comment by ElectricMaxxx** [comment]
Awesome!

**Pull request merged**
