### PR TITLE
[DO NOT MERGE] use same cron as on website

### PR DESCRIPTION
**Pull request by ElectricMaxxx**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
mh, i definetly changed the time from 2:30 -> 1:00 only, so there should be no real difference. So many action here today?

**Comment by ElectricMaxxx** [comment]
I will keep this one open and have a look on tomorrow mornings state of the app.

**Comment by ElectricMaxxx** [comment]
@dbu @lsmith77 does someone of us have ssh access to the platform apps? or shall i add a key to get one. For some reasons the cron doesn't work the way they should do.

**Comment by dbu** [comment]
did it work out? thing is that with each such change, we trigger a redeployment which will also clear up the space.

it smells like we miss log rotation or something like that. i don't know how platform.sh handles those, being specifically for symfony i would expect them to handle the logs out of the box, but maybe they don't.

**Comment by ElectricMaxxx** [comment]
Not sure, we will see, but what i can see in #390 is that a simple `bin/console cache:clear` had not work anymore. I would like to add my key and get ssh support to see logs etc. Not sure if we got it for non enterprice users.

**Pull request merged**
