### PR TITLE
translate seo examples

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by dbu** [comment]
@ElectricMaxxx i did that a while ago but forgot to push. translating and also massaging the german text a bit

**Comment by ElectricMaxxx** [comment]
Travis is also failing on my branch. So let's fix it there. Thanks.

**Comment by ElectricMaxxx** [comment]
Ah i can't merge mobile. @dbu so can you?

**Comment by dbu** [comment]
ah right, was also bitten by that recently. merged. the error looks like something broke when moving the admins.

**Comment by ElectricMaxxx** [comment]
That PR was earlier. Will fix that tonight. Currently mobile only.

**Pull request merged**
