### PR TITLE
adjust some more paths from app to var

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Thanks a lot. The build error looks wired.

**Comment by lsmith77** [comment]
yeah :-/

**Comment by lsmith77** [comment]
BTW .. we might want to also do some simple log rotation to prevent things from filling up the disk .. maybe move the logs daily to a file named by the day of the week or something

**Comment by ElectricMaxxx** [comment]
@lsmith77 but the the file would lay on the same disk and fill it up too? isn't it?
Btw: you got some log/monitor access to our platform.sh instances?

**Comment by dbu** [comment]
if the log file name is only the day of week without date, it should work. but could we just not log to files at all on platform.sh? i don't think anybody ever looks at those files.

i restarted the build, this seems repeatable. it seems to use some "build cache", maybe a one-time fluke got cached in there?

**Comment by dbu** [comment]
i restarted the build on master, and it now fails with the same error. thus its not related to this PR and i will merge it as the fixes look correct.

**Pull request merged**
