### PR TITLE
Configure custom tree browser icons

### PR DESCRIPTION
**Pull request by wouterj**
Configures some custom icons in the CMF sandbox.
## Screenshot

cmf-tree-custom-icons
## Depends on
- [x] https://github.com/symfony-cmf/tree-browser-bundle/pull/120
- [x] https://github.com/symfony-cmf/resource-rest-bundle/pull/38

### CODE REVIEW

**Comment by dbu** [comment]
that looks awesome!

**Comment by wouterj** [comment]
Ready to be merged once https://github.com/symfony-cmf/tree-browser-bundle/pull/120 is merged

**Comment by dbu** [comment]
great! can you please update the dependencies (composer.lock is tracked in git for this repo), now that all prerequisite PRs are merged?

**Comment by wouterj** [comment]
Dependencies updated

**Comment by dbu** [comment]
looking at styleci, i think we miss the setting to allow multiline class declarations

**Comment by wouterj** [comment]
Yeah, but it's only push failure (so failure in the branch itself). The PR styleCI passes, so let's fix that in another pr.

**Pull request merged**
