### PR TITLE
Temporary remove CmfCreateBundle from the sandbox

### PR DESCRIPTION
**Pull request by WouterJ**
Fixes https://github.com/symfony-cmf/cmf-sandbox/issues/312

### CODE REVIEW

**Comment by lsmith77** [comment]
this seems to have broken the demo http://sandbox.cmf.symfony.com

```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'The "/app/vendor/symfony-cmf/create-bundle/Resources/views" directory does not exist.' in /app/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:94 Stack trace: #0 /app/app/cache/prod/appProdProjectContainer.php(4045): Twig_Loader_Filesystem->addPath('/app/vendor/sym...', 'CmfCreate') #1 /app/app/bootstrap.php.cache(2187): appProdProjectContainer->getTwig_LoaderService() #2 /app/app/cache/prod/appProdProjectContainer.php(3966): Symfony\Component\DependencyInjection\Container->get('twig.loader') #3 /app/app/bootstrap.php.cache(2187): appProdProjectContainer->getTwigService() #4 /app/vendor/sonata-project/cache-bundle/SonataCacheBundle.php(29): Symfony\Component\DependencyInjection\Container->get('twig') #5 /app/app/bootstrap.php.cache(2468): Sonata\CacheBundle\SonataCacheBundle->boot() #6 /app/app/bootstrap.php.cache(2496): Symfony\Component\HttpKernel\Kernel->boot() #7 /app/web/app.php(22): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\ in /app/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 94
```

**Comment by WouterJ** [comment]
@lsmith77 seems like the cache has to be cleared (and bootstrap.php.cache has to be regenerated). Do you have ssh access to the sandbox environment to run these commands? (I can't convince my router at home to do ssh...)

**Comment by lsmith77** [comment]
such commands can be run during the build stage:
https://github.com/symfony-cmf/cmf-sandbox/blob/master/.platform.app.yaml#L54

(note after the build stage the file system is read only)

**Comment by WouterJ** [comment]
Merging another PR fixed it: http://sandbox.cmf.symfony.com/en

Seems like the commands weren't run correctly after merging this PR.

**Pull request merged**
