### PR TITLE
Update dependencies to remove deprecations

### PR DESCRIPTION
**Pull request by wouterj**

### CODE REVIEW

**Comment by dbu** [comment]
another version hickup, this time with jms it seems "Call to undefined method Doctrine\ODM\PHPCR\Mapping\ClassMetadata::getField()"

**Comment by WouterJ** [comment]
@dbu yeah, and platformsh has even worse errors :(

**Comment by WouterJ** [comment]
@dbu fixed by using my own repository of JMS. It'll probably take a while before my PR is merged.

**Comment by dbu** [comment]
oh noes! can you please link the jms pull request so we can see when that gets moved?

**Comment by WouterJ** [comment]
@dbu https://github.com/schmittjoh/serializer/pull/605

But please note that the serializer is almost not maintained (latest merge from May 10th, latest release Octobre 27th 2015).

Maybe we can fork the serializer in the symfony-cmf organization and maintain a PHPCR ODM 2.0 compatible branch until the PR is merged?

**Comment by dbu** [comment]
i wonder if such a fork is a good idea. i propose we rather re-add the
BC method for now, until the fix is merged or until jms serializer
decreases enough in popularity that we can simply tell people to not use
it anymore.

**Comment by dbu** [comment]
@WouterJ what do you think of my proposal to re-add the BC method until jms serializer is fixed rather than try to make people use a fork of jms serializer?

**Comment by wouterj** [comment]
I don't like it very much, but it's either maintaining a fork or keeping the BC method.  Keeping the BC method has less change to get out-of-sync,so let's do that (but let's also trigger a deprecation warning)

**Comment by wouterj** [comment]
See https://github.com/doctrine/phpcr-odm/pull/717 , @dbu can you please merge that PR?

**Comment by wouterj** [comment]
🍰

**Comment by dbu** [comment]
uff. thanks wouter!

**Pull request merged**
